//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2__client.EnrollServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnrollServiceReference.EnrollWebServiceSoap")]
    public interface EnrollWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Enroll", ReplyAction="*")]
        bool Enroll(int studentId, int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Enroll", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EnrollAsync(int studentId, int courseId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EnrollWebServiceSoapChannel : Assignment2__client.EnrollServiceReference.EnrollWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnrollWebServiceSoapClient : System.ServiceModel.ClientBase<Assignment2__client.EnrollServiceReference.EnrollWebServiceSoap>, Assignment2__client.EnrollServiceReference.EnrollWebServiceSoap {
        
        public EnrollWebServiceSoapClient() {
        }
        
        public EnrollWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnrollWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnrollWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnrollWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Enroll(int studentId, int courseId) {
            return base.Channel.Enroll(studentId, courseId);
        }
        
        public System.Threading.Tasks.Task<bool> EnrollAsync(int studentId, int courseId) {
            return base.Channel.EnrollAsync(studentId, courseId);
        }
    }
}
