//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2__client.StudentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CStudent", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CStudent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Assignment2__client.StudentServiceReference.CCourse[] CoursesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StudentCode {
            get {
                return this.StudentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentCodeField, value) != true)) {
                    this.StudentCodeField = value;
                    this.RaisePropertyChanged("StudentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StudentName {
            get {
                return this.StudentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNameField, value) != true)) {
                    this.StudentNameField = value;
                    this.RaisePropertyChanged("StudentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NIC {
            get {
                return this.NICField;
            }
            set {
                if ((object.ReferenceEquals(this.NICField, value) != true)) {
                    this.NICField = value;
                    this.RaisePropertyChanged("NIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ContactPerson {
            get {
                return this.ContactPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonField, value) != true)) {
                    this.ContactPersonField = value;
                    this.RaisePropertyChanged("ContactPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Assignment2__client.StudentServiceReference.CCourse[] Courses {
            get {
                return this.CoursesField;
            }
            set {
                if ((object.ReferenceEquals(this.CoursesField, value) != true)) {
                    this.CoursesField = value;
                    this.RaisePropertyChanged("Courses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CCourse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CCourse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CourseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        private int CourseCreditsField;
        
        private int SemesterNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Assignment2__client.StudentServiceReference.CStudent[] StudentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CourseId {
            get {
                return this.CourseIdField;
            }
            set {
                if ((this.CourseIdField.Equals(value) != true)) {
                    this.CourseIdField = value;
                    this.RaisePropertyChanged("CourseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CourseCode {
            get {
                return this.CourseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseCodeField, value) != true)) {
                    this.CourseCodeField = value;
                    this.RaisePropertyChanged("CourseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CourseCredits {
            get {
                return this.CourseCreditsField;
            }
            set {
                if ((this.CourseCreditsField.Equals(value) != true)) {
                    this.CourseCreditsField = value;
                    this.RaisePropertyChanged("CourseCredits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SemesterNumber {
            get {
                return this.SemesterNumberField;
            }
            set {
                if ((this.SemesterNumberField.Equals(value) != true)) {
                    this.SemesterNumberField = value;
                    this.RaisePropertyChanged("SemesterNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Assignment2__client.StudentServiceReference.CStudent[] Students {
            get {
                return this.StudentsField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentsField, value) != true)) {
                    this.StudentsField = value;
                    this.RaisePropertyChanged("Students");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentServiceReference.StudentWebServiceSoap")]
    public interface StudentWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllStudentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStudents", ReplyAction="*")]
        Assignment2__client.StudentServiceReference.GetAllStudentsResponse GetAllStudents(Assignment2__client.StudentServiceReference.GetAllStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.GetAllStudentsResponse> GetAllStudentsAsync(Assignment2__client.StudentServiceReference.GetAllStudentsRequest request);
        
        // CODEGEN: Generating message contract since element name classStudent from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStudent", ReplyAction="*")]
        Assignment2__client.StudentServiceReference.AddStudentResponse AddStudent(Assignment2__client.StudentServiceReference.AddStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.AddStudentResponse> AddStudentAsync(Assignment2__client.StudentServiceReference.AddStudentRequest request);
        
        // CODEGEN: Generating message contract since element name classStudent from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveStudent", ReplyAction="*")]
        Assignment2__client.StudentServiceReference.SaveStudentResponse SaveStudent(Assignment2__client.StudentServiceReference.SaveStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.SaveStudentResponse> SaveStudentAsync(Assignment2__client.StudentServiceReference.SaveStudentRequest request);
        
        // CODEGEN: Generating message contract since element name studentName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchStudents", ReplyAction="*")]
        Assignment2__client.StudentServiceReference.SearchStudentsResponse SearchStudents(Assignment2__client.StudentServiceReference.SearchStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.SearchStudentsResponse> SearchStudentsAsync(Assignment2__client.StudentServiceReference.SearchStudentsRequest request);
        
        // CODEGEN: Generating message contract since element name GetStudentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudent", ReplyAction="*")]
        Assignment2__client.StudentServiceReference.GetStudentResponse GetStudent(Assignment2__client.StudentServiceReference.GetStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.GetStudentResponse> GetStudentAsync(Assignment2__client.StudentServiceReference.GetStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteStudent", ReplyAction="*")]
        bool DeleteStudent(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteStudentAsync(int studentId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudents", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.StudentServiceReference.GetAllStudentsRequestBody Body;
        
        public GetAllStudentsRequest() {
        }
        
        public GetAllStudentsRequest(Assignment2__client.StudentServiceReference.GetAllStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllStudentsRequestBody {
        
        public GetAllStudentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.StudentServiceReference.GetAllStudentsResponseBody Body;
        
        public GetAllStudentsResponse() {
        }
        
        public GetAllStudentsResponse(Assignment2__client.StudentServiceReference.GetAllStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllStudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2__client.StudentServiceReference.CStudent[] GetAllStudentsResult;
        
        public GetAllStudentsResponseBody() {
        }
        
        public GetAllStudentsResponseBody(Assignment2__client.StudentServiceReference.CStudent[] GetAllStudentsResult) {
            this.GetAllStudentsResult = GetAllStudentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStudent", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.StudentServiceReference.AddStudentRequestBody Body;
        
        public AddStudentRequest() {
        }
        
        public AddStudentRequest(Assignment2__client.StudentServiceReference.AddStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2__client.StudentServiceReference.CStudent classStudent;
        
        public AddStudentRequestBody() {
        }
        
        public AddStudentRequestBody(Assignment2__client.StudentServiceReference.CStudent classStudent) {
            this.classStudent = classStudent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.StudentServiceReference.AddStudentResponseBody Body;
        
        public AddStudentResponse() {
        }
        
        public AddStudentResponse(Assignment2__client.StudentServiceReference.AddStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddStudentResult;
        
        public AddStudentResponseBody() {
        }
        
        public AddStudentResponseBody(bool AddStudentResult) {
            this.AddStudentResult = AddStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveStudent", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.StudentServiceReference.SaveStudentRequestBody Body;
        
        public SaveStudentRequest() {
        }
        
        public SaveStudentRequest(Assignment2__client.StudentServiceReference.SaveStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2__client.StudentServiceReference.CStudent classStudent;
        
        public SaveStudentRequestBody() {
        }
        
        public SaveStudentRequestBody(Assignment2__client.StudentServiceReference.CStudent classStudent) {
            this.classStudent = classStudent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.StudentServiceReference.SaveStudentResponseBody Body;
        
        public SaveStudentResponse() {
        }
        
        public SaveStudentResponse(Assignment2__client.StudentServiceReference.SaveStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveStudentResult;
        
        public SaveStudentResponseBody() {
        }
        
        public SaveStudentResponseBody(bool SaveStudentResult) {
            this.SaveStudentResult = SaveStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchStudents", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.StudentServiceReference.SearchStudentsRequestBody Body;
        
        public SearchStudentsRequest() {
        }
        
        public SearchStudentsRequest(Assignment2__client.StudentServiceReference.SearchStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchStudentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string studentName;
        
        public SearchStudentsRequestBody() {
        }
        
        public SearchStudentsRequestBody(string studentName) {
            this.studentName = studentName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchStudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.StudentServiceReference.SearchStudentsResponseBody Body;
        
        public SearchStudentsResponse() {
        }
        
        public SearchStudentsResponse(Assignment2__client.StudentServiceReference.SearchStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchStudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2__client.StudentServiceReference.CStudent[] SearchStudentsResult;
        
        public SearchStudentsResponseBody() {
        }
        
        public SearchStudentsResponseBody(Assignment2__client.StudentServiceReference.CStudent[] SearchStudentsResult) {
            this.SearchStudentsResult = SearchStudentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudent", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.StudentServiceReference.GetStudentRequestBody Body;
        
        public GetStudentRequest() {
        }
        
        public GetStudentRequest(Assignment2__client.StudentServiceReference.GetStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int studentId;
        
        public GetStudentRequestBody() {
        }
        
        public GetStudentRequestBody(int studentId) {
            this.studentId = studentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.StudentServiceReference.GetStudentResponseBody Body;
        
        public GetStudentResponse() {
        }
        
        public GetStudentResponse(Assignment2__client.StudentServiceReference.GetStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2__client.StudentServiceReference.CStudent GetStudentResult;
        
        public GetStudentResponseBody() {
        }
        
        public GetStudentResponseBody(Assignment2__client.StudentServiceReference.CStudent GetStudentResult) {
            this.GetStudentResult = GetStudentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentWebServiceSoapChannel : Assignment2__client.StudentServiceReference.StudentWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentWebServiceSoapClient : System.ServiceModel.ClientBase<Assignment2__client.StudentServiceReference.StudentWebServiceSoap>, Assignment2__client.StudentServiceReference.StudentWebServiceSoap {
        
        public StudentWebServiceSoapClient() {
        }
        
        public StudentWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2__client.StudentServiceReference.GetAllStudentsResponse Assignment2__client.StudentServiceReference.StudentWebServiceSoap.GetAllStudents(Assignment2__client.StudentServiceReference.GetAllStudentsRequest request) {
            return base.Channel.GetAllStudents(request);
        }
        
        public Assignment2__client.StudentServiceReference.CStudent[] GetAllStudents() {
            Assignment2__client.StudentServiceReference.GetAllStudentsRequest inValue = new Assignment2__client.StudentServiceReference.GetAllStudentsRequest();
            inValue.Body = new Assignment2__client.StudentServiceReference.GetAllStudentsRequestBody();
            Assignment2__client.StudentServiceReference.GetAllStudentsResponse retVal = ((Assignment2__client.StudentServiceReference.StudentWebServiceSoap)(this)).GetAllStudents(inValue);
            return retVal.Body.GetAllStudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.GetAllStudentsResponse> Assignment2__client.StudentServiceReference.StudentWebServiceSoap.GetAllStudentsAsync(Assignment2__client.StudentServiceReference.GetAllStudentsRequest request) {
            return base.Channel.GetAllStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.GetAllStudentsResponse> GetAllStudentsAsync() {
            Assignment2__client.StudentServiceReference.GetAllStudentsRequest inValue = new Assignment2__client.StudentServiceReference.GetAllStudentsRequest();
            inValue.Body = new Assignment2__client.StudentServiceReference.GetAllStudentsRequestBody();
            return ((Assignment2__client.StudentServiceReference.StudentWebServiceSoap)(this)).GetAllStudentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2__client.StudentServiceReference.AddStudentResponse Assignment2__client.StudentServiceReference.StudentWebServiceSoap.AddStudent(Assignment2__client.StudentServiceReference.AddStudentRequest request) {
            return base.Channel.AddStudent(request);
        }
        
        public bool AddStudent(Assignment2__client.StudentServiceReference.CStudent classStudent) {
            Assignment2__client.StudentServiceReference.AddStudentRequest inValue = new Assignment2__client.StudentServiceReference.AddStudentRequest();
            inValue.Body = new Assignment2__client.StudentServiceReference.AddStudentRequestBody();
            inValue.Body.classStudent = classStudent;
            Assignment2__client.StudentServiceReference.AddStudentResponse retVal = ((Assignment2__client.StudentServiceReference.StudentWebServiceSoap)(this)).AddStudent(inValue);
            return retVal.Body.AddStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.AddStudentResponse> Assignment2__client.StudentServiceReference.StudentWebServiceSoap.AddStudentAsync(Assignment2__client.StudentServiceReference.AddStudentRequest request) {
            return base.Channel.AddStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.AddStudentResponse> AddStudentAsync(Assignment2__client.StudentServiceReference.CStudent classStudent) {
            Assignment2__client.StudentServiceReference.AddStudentRequest inValue = new Assignment2__client.StudentServiceReference.AddStudentRequest();
            inValue.Body = new Assignment2__client.StudentServiceReference.AddStudentRequestBody();
            inValue.Body.classStudent = classStudent;
            return ((Assignment2__client.StudentServiceReference.StudentWebServiceSoap)(this)).AddStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2__client.StudentServiceReference.SaveStudentResponse Assignment2__client.StudentServiceReference.StudentWebServiceSoap.SaveStudent(Assignment2__client.StudentServiceReference.SaveStudentRequest request) {
            return base.Channel.SaveStudent(request);
        }
        
        public bool SaveStudent(Assignment2__client.StudentServiceReference.CStudent classStudent) {
            Assignment2__client.StudentServiceReference.SaveStudentRequest inValue = new Assignment2__client.StudentServiceReference.SaveStudentRequest();
            inValue.Body = new Assignment2__client.StudentServiceReference.SaveStudentRequestBody();
            inValue.Body.classStudent = classStudent;
            Assignment2__client.StudentServiceReference.SaveStudentResponse retVal = ((Assignment2__client.StudentServiceReference.StudentWebServiceSoap)(this)).SaveStudent(inValue);
            return retVal.Body.SaveStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.SaveStudentResponse> Assignment2__client.StudentServiceReference.StudentWebServiceSoap.SaveStudentAsync(Assignment2__client.StudentServiceReference.SaveStudentRequest request) {
            return base.Channel.SaveStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.SaveStudentResponse> SaveStudentAsync(Assignment2__client.StudentServiceReference.CStudent classStudent) {
            Assignment2__client.StudentServiceReference.SaveStudentRequest inValue = new Assignment2__client.StudentServiceReference.SaveStudentRequest();
            inValue.Body = new Assignment2__client.StudentServiceReference.SaveStudentRequestBody();
            inValue.Body.classStudent = classStudent;
            return ((Assignment2__client.StudentServiceReference.StudentWebServiceSoap)(this)).SaveStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2__client.StudentServiceReference.SearchStudentsResponse Assignment2__client.StudentServiceReference.StudentWebServiceSoap.SearchStudents(Assignment2__client.StudentServiceReference.SearchStudentsRequest request) {
            return base.Channel.SearchStudents(request);
        }
        
        public Assignment2__client.StudentServiceReference.CStudent[] SearchStudents(string studentName) {
            Assignment2__client.StudentServiceReference.SearchStudentsRequest inValue = new Assignment2__client.StudentServiceReference.SearchStudentsRequest();
            inValue.Body = new Assignment2__client.StudentServiceReference.SearchStudentsRequestBody();
            inValue.Body.studentName = studentName;
            Assignment2__client.StudentServiceReference.SearchStudentsResponse retVal = ((Assignment2__client.StudentServiceReference.StudentWebServiceSoap)(this)).SearchStudents(inValue);
            return retVal.Body.SearchStudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.SearchStudentsResponse> Assignment2__client.StudentServiceReference.StudentWebServiceSoap.SearchStudentsAsync(Assignment2__client.StudentServiceReference.SearchStudentsRequest request) {
            return base.Channel.SearchStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.SearchStudentsResponse> SearchStudentsAsync(string studentName) {
            Assignment2__client.StudentServiceReference.SearchStudentsRequest inValue = new Assignment2__client.StudentServiceReference.SearchStudentsRequest();
            inValue.Body = new Assignment2__client.StudentServiceReference.SearchStudentsRequestBody();
            inValue.Body.studentName = studentName;
            return ((Assignment2__client.StudentServiceReference.StudentWebServiceSoap)(this)).SearchStudentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2__client.StudentServiceReference.GetStudentResponse Assignment2__client.StudentServiceReference.StudentWebServiceSoap.GetStudent(Assignment2__client.StudentServiceReference.GetStudentRequest request) {
            return base.Channel.GetStudent(request);
        }
        
        public Assignment2__client.StudentServiceReference.CStudent GetStudent(int studentId) {
            Assignment2__client.StudentServiceReference.GetStudentRequest inValue = new Assignment2__client.StudentServiceReference.GetStudentRequest();
            inValue.Body = new Assignment2__client.StudentServiceReference.GetStudentRequestBody();
            inValue.Body.studentId = studentId;
            Assignment2__client.StudentServiceReference.GetStudentResponse retVal = ((Assignment2__client.StudentServiceReference.StudentWebServiceSoap)(this)).GetStudent(inValue);
            return retVal.Body.GetStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.GetStudentResponse> Assignment2__client.StudentServiceReference.StudentWebServiceSoap.GetStudentAsync(Assignment2__client.StudentServiceReference.GetStudentRequest request) {
            return base.Channel.GetStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment2__client.StudentServiceReference.GetStudentResponse> GetStudentAsync(int studentId) {
            Assignment2__client.StudentServiceReference.GetStudentRequest inValue = new Assignment2__client.StudentServiceReference.GetStudentRequest();
            inValue.Body = new Assignment2__client.StudentServiceReference.GetStudentRequestBody();
            inValue.Body.studentId = studentId;
            return ((Assignment2__client.StudentServiceReference.StudentWebServiceSoap)(this)).GetStudentAsync(inValue);
        }
        
        public bool DeleteStudent(int studentId) {
            return base.Channel.DeleteStudent(studentId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStudentAsync(int studentId) {
            return base.Channel.DeleteStudentAsync(studentId);
        }
    }
}
