//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2__client.CourseServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CCourse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CCourse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CourseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        private int CourseCreditsField;
        
        private int SemesterNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Assignment2__client.CourseServiceReference.CStudent[] StudentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CourseId {
            get {
                return this.CourseIdField;
            }
            set {
                if ((this.CourseIdField.Equals(value) != true)) {
                    this.CourseIdField = value;
                    this.RaisePropertyChanged("CourseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CourseCode {
            get {
                return this.CourseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseCodeField, value) != true)) {
                    this.CourseCodeField = value;
                    this.RaisePropertyChanged("CourseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CourseCredits {
            get {
                return this.CourseCreditsField;
            }
            set {
                if ((this.CourseCreditsField.Equals(value) != true)) {
                    this.CourseCreditsField = value;
                    this.RaisePropertyChanged("CourseCredits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SemesterNumber {
            get {
                return this.SemesterNumberField;
            }
            set {
                if ((this.SemesterNumberField.Equals(value) != true)) {
                    this.SemesterNumberField = value;
                    this.RaisePropertyChanged("SemesterNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Assignment2__client.CourseServiceReference.CStudent[] Students {
            get {
                return this.StudentsField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentsField, value) != true)) {
                    this.StudentsField = value;
                    this.RaisePropertyChanged("Students");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CStudent", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CStudent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Assignment2__client.CourseServiceReference.CCourse[] CoursesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StudentCode {
            get {
                return this.StudentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentCodeField, value) != true)) {
                    this.StudentCodeField = value;
                    this.RaisePropertyChanged("StudentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StudentName {
            get {
                return this.StudentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNameField, value) != true)) {
                    this.StudentNameField = value;
                    this.RaisePropertyChanged("StudentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NIC {
            get {
                return this.NICField;
            }
            set {
                if ((object.ReferenceEquals(this.NICField, value) != true)) {
                    this.NICField = value;
                    this.RaisePropertyChanged("NIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ContactPerson {
            get {
                return this.ContactPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonField, value) != true)) {
                    this.ContactPersonField = value;
                    this.RaisePropertyChanged("ContactPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Assignment2__client.CourseServiceReference.CCourse[] Courses {
            get {
                return this.CoursesField;
            }
            set {
                if ((object.ReferenceEquals(this.CoursesField, value) != true)) {
                    this.CoursesField = value;
                    this.RaisePropertyChanged("Courses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CourseServiceReference.CourseWebServiceSoap")]
    public interface CourseWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllCoursesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCourses", ReplyAction="*")]
        Assignment2__client.CourseServiceReference.GetAllCoursesResponse GetAllCourses(Assignment2__client.CourseServiceReference.GetAllCoursesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCourses", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.GetAllCoursesResponse> GetAllCoursesAsync(Assignment2__client.CourseServiceReference.GetAllCoursesRequest request);
        
        // CODEGEN: Generating message contract since element name cCourse from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCourse", ReplyAction="*")]
        Assignment2__client.CourseServiceReference.AddCourseResponse AddCourse(Assignment2__client.CourseServiceReference.AddCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.AddCourseResponse> AddCourseAsync(Assignment2__client.CourseServiceReference.AddCourseRequest request);
        
        // CODEGEN: Generating message contract since element name cCourse from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveCourse", ReplyAction="*")]
        Assignment2__client.CourseServiceReference.SaveCourseResponse SaveCourse(Assignment2__client.CourseServiceReference.SaveCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.SaveCourseResponse> SaveCourseAsync(Assignment2__client.CourseServiceReference.SaveCourseRequest request);
        
        // CODEGEN: Generating message contract since element name coursename from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchCourses", ReplyAction="*")]
        Assignment2__client.CourseServiceReference.SearchCoursesResponse SearchCourses(Assignment2__client.CourseServiceReference.SearchCoursesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchCourses", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.SearchCoursesResponse> SearchCoursesAsync(Assignment2__client.CourseServiceReference.SearchCoursesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCourseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCourse", ReplyAction="*")]
        Assignment2__client.CourseServiceReference.GetCourseResponse GetCourse(Assignment2__client.CourseServiceReference.GetCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.GetCourseResponse> GetCourseAsync(Assignment2__client.CourseServiceReference.GetCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCourse", ReplyAction="*")]
        bool DeleteCourse(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCourseAsync(int studentId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCoursesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCourses", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.CourseServiceReference.GetAllCoursesRequestBody Body;
        
        public GetAllCoursesRequest() {
        }
        
        public GetAllCoursesRequest(Assignment2__client.CourseServiceReference.GetAllCoursesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCoursesRequestBody {
        
        public GetAllCoursesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCoursesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.CourseServiceReference.GetAllCoursesResponseBody Body;
        
        public GetAllCoursesResponse() {
        }
        
        public GetAllCoursesResponse(Assignment2__client.CourseServiceReference.GetAllCoursesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCoursesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2__client.CourseServiceReference.CCourse[] GetAllCoursesResult;
        
        public GetAllCoursesResponseBody() {
        }
        
        public GetAllCoursesResponseBody(Assignment2__client.CourseServiceReference.CCourse[] GetAllCoursesResult) {
            this.GetAllCoursesResult = GetAllCoursesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCourse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.CourseServiceReference.AddCourseRequestBody Body;
        
        public AddCourseRequest() {
        }
        
        public AddCourseRequest(Assignment2__client.CourseServiceReference.AddCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2__client.CourseServiceReference.CCourse cCourse;
        
        public AddCourseRequestBody() {
        }
        
        public AddCourseRequestBody(Assignment2__client.CourseServiceReference.CCourse cCourse) {
            this.cCourse = cCourse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.CourseServiceReference.AddCourseResponseBody Body;
        
        public AddCourseResponse() {
        }
        
        public AddCourseResponse(Assignment2__client.CourseServiceReference.AddCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddCourseResult;
        
        public AddCourseResponseBody() {
        }
        
        public AddCourseResponseBody(bool AddCourseResult) {
            this.AddCourseResult = AddCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCourse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.CourseServiceReference.SaveCourseRequestBody Body;
        
        public SaveCourseRequest() {
        }
        
        public SaveCourseRequest(Assignment2__client.CourseServiceReference.SaveCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2__client.CourseServiceReference.CCourse cCourse;
        
        public SaveCourseRequestBody() {
        }
        
        public SaveCourseRequestBody(Assignment2__client.CourseServiceReference.CCourse cCourse) {
            this.cCourse = cCourse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.CourseServiceReference.SaveCourseResponseBody Body;
        
        public SaveCourseResponse() {
        }
        
        public SaveCourseResponse(Assignment2__client.CourseServiceReference.SaveCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveCourseResult;
        
        public SaveCourseResponseBody() {
        }
        
        public SaveCourseResponseBody(bool SaveCourseResult) {
            this.SaveCourseResult = SaveCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchCoursesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchCourses", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.CourseServiceReference.SearchCoursesRequestBody Body;
        
        public SearchCoursesRequest() {
        }
        
        public SearchCoursesRequest(Assignment2__client.CourseServiceReference.SearchCoursesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchCoursesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string coursename;
        
        public SearchCoursesRequestBody() {
        }
        
        public SearchCoursesRequestBody(string coursename) {
            this.coursename = coursename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchCoursesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.CourseServiceReference.SearchCoursesResponseBody Body;
        
        public SearchCoursesResponse() {
        }
        
        public SearchCoursesResponse(Assignment2__client.CourseServiceReference.SearchCoursesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchCoursesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2__client.CourseServiceReference.CCourse[] SearchCoursesResult;
        
        public SearchCoursesResponseBody() {
        }
        
        public SearchCoursesResponseBody(Assignment2__client.CourseServiceReference.CCourse[] SearchCoursesResult) {
            this.SearchCoursesResult = SearchCoursesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.CourseServiceReference.GetCourseRequestBody Body;
        
        public GetCourseRequest() {
        }
        
        public GetCourseRequest(Assignment2__client.CourseServiceReference.GetCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int courseId;
        
        public GetCourseRequestBody() {
        }
        
        public GetCourseRequestBody(int courseId) {
            this.courseId = courseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2__client.CourseServiceReference.GetCourseResponseBody Body;
        
        public GetCourseResponse() {
        }
        
        public GetCourseResponse(Assignment2__client.CourseServiceReference.GetCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2__client.CourseServiceReference.CCourse GetCourseResult;
        
        public GetCourseResponseBody() {
        }
        
        public GetCourseResponseBody(Assignment2__client.CourseServiceReference.CCourse GetCourseResult) {
            this.GetCourseResult = GetCourseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CourseWebServiceSoapChannel : Assignment2__client.CourseServiceReference.CourseWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseWebServiceSoapClient : System.ServiceModel.ClientBase<Assignment2__client.CourseServiceReference.CourseWebServiceSoap>, Assignment2__client.CourseServiceReference.CourseWebServiceSoap {
        
        public CourseWebServiceSoapClient() {
        }
        
        public CourseWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2__client.CourseServiceReference.GetAllCoursesResponse Assignment2__client.CourseServiceReference.CourseWebServiceSoap.GetAllCourses(Assignment2__client.CourseServiceReference.GetAllCoursesRequest request) {
            return base.Channel.GetAllCourses(request);
        }
        
        public Assignment2__client.CourseServiceReference.CCourse[] GetAllCourses() {
            Assignment2__client.CourseServiceReference.GetAllCoursesRequest inValue = new Assignment2__client.CourseServiceReference.GetAllCoursesRequest();
            inValue.Body = new Assignment2__client.CourseServiceReference.GetAllCoursesRequestBody();
            Assignment2__client.CourseServiceReference.GetAllCoursesResponse retVal = ((Assignment2__client.CourseServiceReference.CourseWebServiceSoap)(this)).GetAllCourses(inValue);
            return retVal.Body.GetAllCoursesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.GetAllCoursesResponse> Assignment2__client.CourseServiceReference.CourseWebServiceSoap.GetAllCoursesAsync(Assignment2__client.CourseServiceReference.GetAllCoursesRequest request) {
            return base.Channel.GetAllCoursesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.GetAllCoursesResponse> GetAllCoursesAsync() {
            Assignment2__client.CourseServiceReference.GetAllCoursesRequest inValue = new Assignment2__client.CourseServiceReference.GetAllCoursesRequest();
            inValue.Body = new Assignment2__client.CourseServiceReference.GetAllCoursesRequestBody();
            return ((Assignment2__client.CourseServiceReference.CourseWebServiceSoap)(this)).GetAllCoursesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2__client.CourseServiceReference.AddCourseResponse Assignment2__client.CourseServiceReference.CourseWebServiceSoap.AddCourse(Assignment2__client.CourseServiceReference.AddCourseRequest request) {
            return base.Channel.AddCourse(request);
        }
        
        public bool AddCourse(Assignment2__client.CourseServiceReference.CCourse cCourse) {
            Assignment2__client.CourseServiceReference.AddCourseRequest inValue = new Assignment2__client.CourseServiceReference.AddCourseRequest();
            inValue.Body = new Assignment2__client.CourseServiceReference.AddCourseRequestBody();
            inValue.Body.cCourse = cCourse;
            Assignment2__client.CourseServiceReference.AddCourseResponse retVal = ((Assignment2__client.CourseServiceReference.CourseWebServiceSoap)(this)).AddCourse(inValue);
            return retVal.Body.AddCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.AddCourseResponse> Assignment2__client.CourseServiceReference.CourseWebServiceSoap.AddCourseAsync(Assignment2__client.CourseServiceReference.AddCourseRequest request) {
            return base.Channel.AddCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.AddCourseResponse> AddCourseAsync(Assignment2__client.CourseServiceReference.CCourse cCourse) {
            Assignment2__client.CourseServiceReference.AddCourseRequest inValue = new Assignment2__client.CourseServiceReference.AddCourseRequest();
            inValue.Body = new Assignment2__client.CourseServiceReference.AddCourseRequestBody();
            inValue.Body.cCourse = cCourse;
            return ((Assignment2__client.CourseServiceReference.CourseWebServiceSoap)(this)).AddCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2__client.CourseServiceReference.SaveCourseResponse Assignment2__client.CourseServiceReference.CourseWebServiceSoap.SaveCourse(Assignment2__client.CourseServiceReference.SaveCourseRequest request) {
            return base.Channel.SaveCourse(request);
        }
        
        public bool SaveCourse(Assignment2__client.CourseServiceReference.CCourse cCourse) {
            Assignment2__client.CourseServiceReference.SaveCourseRequest inValue = new Assignment2__client.CourseServiceReference.SaveCourseRequest();
            inValue.Body = new Assignment2__client.CourseServiceReference.SaveCourseRequestBody();
            inValue.Body.cCourse = cCourse;
            Assignment2__client.CourseServiceReference.SaveCourseResponse retVal = ((Assignment2__client.CourseServiceReference.CourseWebServiceSoap)(this)).SaveCourse(inValue);
            return retVal.Body.SaveCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.SaveCourseResponse> Assignment2__client.CourseServiceReference.CourseWebServiceSoap.SaveCourseAsync(Assignment2__client.CourseServiceReference.SaveCourseRequest request) {
            return base.Channel.SaveCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.SaveCourseResponse> SaveCourseAsync(Assignment2__client.CourseServiceReference.CCourse cCourse) {
            Assignment2__client.CourseServiceReference.SaveCourseRequest inValue = new Assignment2__client.CourseServiceReference.SaveCourseRequest();
            inValue.Body = new Assignment2__client.CourseServiceReference.SaveCourseRequestBody();
            inValue.Body.cCourse = cCourse;
            return ((Assignment2__client.CourseServiceReference.CourseWebServiceSoap)(this)).SaveCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2__client.CourseServiceReference.SearchCoursesResponse Assignment2__client.CourseServiceReference.CourseWebServiceSoap.SearchCourses(Assignment2__client.CourseServiceReference.SearchCoursesRequest request) {
            return base.Channel.SearchCourses(request);
        }
        
        public Assignment2__client.CourseServiceReference.CCourse[] SearchCourses(string coursename) {
            Assignment2__client.CourseServiceReference.SearchCoursesRequest inValue = new Assignment2__client.CourseServiceReference.SearchCoursesRequest();
            inValue.Body = new Assignment2__client.CourseServiceReference.SearchCoursesRequestBody();
            inValue.Body.coursename = coursename;
            Assignment2__client.CourseServiceReference.SearchCoursesResponse retVal = ((Assignment2__client.CourseServiceReference.CourseWebServiceSoap)(this)).SearchCourses(inValue);
            return retVal.Body.SearchCoursesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.SearchCoursesResponse> Assignment2__client.CourseServiceReference.CourseWebServiceSoap.SearchCoursesAsync(Assignment2__client.CourseServiceReference.SearchCoursesRequest request) {
            return base.Channel.SearchCoursesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.SearchCoursesResponse> SearchCoursesAsync(string coursename) {
            Assignment2__client.CourseServiceReference.SearchCoursesRequest inValue = new Assignment2__client.CourseServiceReference.SearchCoursesRequest();
            inValue.Body = new Assignment2__client.CourseServiceReference.SearchCoursesRequestBody();
            inValue.Body.coursename = coursename;
            return ((Assignment2__client.CourseServiceReference.CourseWebServiceSoap)(this)).SearchCoursesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2__client.CourseServiceReference.GetCourseResponse Assignment2__client.CourseServiceReference.CourseWebServiceSoap.GetCourse(Assignment2__client.CourseServiceReference.GetCourseRequest request) {
            return base.Channel.GetCourse(request);
        }
        
        public Assignment2__client.CourseServiceReference.CCourse GetCourse(int courseId) {
            Assignment2__client.CourseServiceReference.GetCourseRequest inValue = new Assignment2__client.CourseServiceReference.GetCourseRequest();
            inValue.Body = new Assignment2__client.CourseServiceReference.GetCourseRequestBody();
            inValue.Body.courseId = courseId;
            Assignment2__client.CourseServiceReference.GetCourseResponse retVal = ((Assignment2__client.CourseServiceReference.CourseWebServiceSoap)(this)).GetCourse(inValue);
            return retVal.Body.GetCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.GetCourseResponse> Assignment2__client.CourseServiceReference.CourseWebServiceSoap.GetCourseAsync(Assignment2__client.CourseServiceReference.GetCourseRequest request) {
            return base.Channel.GetCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment2__client.CourseServiceReference.GetCourseResponse> GetCourseAsync(int courseId) {
            Assignment2__client.CourseServiceReference.GetCourseRequest inValue = new Assignment2__client.CourseServiceReference.GetCourseRequest();
            inValue.Body = new Assignment2__client.CourseServiceReference.GetCourseRequestBody();
            inValue.Body.courseId = courseId;
            return ((Assignment2__client.CourseServiceReference.CourseWebServiceSoap)(this)).GetCourseAsync(inValue);
        }
        
        public bool DeleteCourse(int studentId) {
            return base.Channel.DeleteCourse(studentId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCourseAsync(int studentId) {
            return base.Channel.DeleteCourseAsync(studentId);
        }
    }
}
